## Basic Configuration
baseurl = "https://example.com/"
languageCode = "en"

theme = "tale"

title = "Always Blank"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Ben"
    # description = "..."
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "alwaysblank"
    twitter = "isalwaysblank"
    stackoverflow = "8099010"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Work"
    identifier = "work"
    weight = 200
    url = "/work/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
