---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Sites
- type: directory
  path: content/case-studies
  label: Case Studies
  create: documents
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - case-study
- type: document
  path: content/_data/sites.json
  label: List
upload_dir: alwaysblank.org
public_path: https://res.cloudinary.com/djd6kxozp/image/upload/f_auto,q_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
